<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/30 20:07:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=hormigon_asturiana;host=localhost',
  'username' => 'hormigon',
  'password' => 'H0rm160n',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    'DEFAULT_TABLE_TYPE' => 'INNODB',
    'DEFAULT_TABLE_CHARSET' => 'utf8',
    'DEFAULT_TABLE_COLLATE' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
