<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/10/01 10:10:51
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'image' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'tags' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
