<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/10/01 13:38:05
sfConfig::add(array(
  'mod_taggablecomplete_enabled' => true,
  'mod_taggablecomplete_view_class' => 'sfPHP',
));
