<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/10/14 12:55:07
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
